<?php

return array(
	'version' => '0.9.3',
	'notes.need_empty_minify' => false,
	'pgcache.enabled' => true,
	'pgcache.engine' => 'file_generic',
	'minify.enabled' => false,
	'minify.auto' => true,
	'minify.engine' => 'file',
	'minify.html.engine' => 'html',
	'minify.js.engine' => 'js',
	'minify.css.engine' => 'css',
	'dbcache.enabled' => false,
	'dbcache.engine' => 'file',
	'objectcache.enabled' => false,
	'objectcache.engine' => 'file',
	'browsercache.enabled' => true,
	'cdn.enabled' => false,
	'cdn.engine' => 'maxcdn',
	'varnish.enabled' => false,
	'varnish.servers' => array(
		0 => '',
	),
	'cloudflare.enabled' => false,
	'cloudflare.email' => '',
	'cloudflare.key' => '',
	'cloudflare.zone' => '',
	'newrelic.enabled' => false,
	'newrelic.api_key' => '',
	'newrelic.account_id' => '',
	'newrelic.appname' => '',
	'newrelic.application_id' => 0,
	'plugin.license_key' => '',
	'widget.pagespeed.enabled' => true,
	'widget.pagespeed.key' => '',
	'config.check' => true,
	'pgcache.file.nfs' => false,
	'minify.file.nfs' => false,
	'dbcache.file.locking' => false,
	'objectcache.file.locking' => false,
	'pgcache.file.locking' => false,
	'minify.file.locking' => false,
	'common.instance_id' => 1781306250,
	'notes.need_empty_pgcache' => false,
	'pgcache.debug' => false,
	'minify.debug' => false,
	'notes.plugins_updated' => true,
	'minify.rewrite' => false,
	'minify.reject.logged' => false,
	'minify.html.enable' => false,
	'minify.html.inline.css' => false,
	'minify.html.inline.js' => false,
	'minify.html.reject.feed' => true,
	'minify.html.strip.crlf' => false,
	'minify.html.comments.ignore' => array(
		0 => 'google_ad_',
		1 => 'RSPEAK_',
	),
	'minify.js.enable' => false,
	'minify.js.combine.header' => true,
	'minify.js.header.embed_type' => 'nb-async',
	'minify.js.combine.body' => false,
	'minify.js.body.embed_type' => 'nb-async',
	'minify.js.combine.footer' => false,
	'minify.js.footer.embed_type' => 'nb-async',
	'minify.js.strip.comments' => false,
	'minify.js.strip.crlf' => false,
	'minify.css.enable' => false,
	'minify.css.combine' => true,
	'minify.css.strip.comments' => false,
	'minify.css.strip.crlf' => false,
	'minify.css.imports' => '',
	'minify.lifetime' => 86400,
	'minify.file.gc' => 86400,
	'minify.reject.uri' => array(
		0 => '',
	),
	'minify.reject.files.js' => array(
		0 => '',
	),
	'minify.reject.files.css' => array(
		0 => '',
	),
	'minify.reject.ua' => array(
		0 => '',
	),
	'minify.js.groups' => array(
		'3919b' => array(
			'default' => array(
				'include' => array(
					'files' => array(
						0 => 'https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js',
						1 => '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js',
						2 => 'http://www.theharrington.com/v3/wp-includes/js/jquery/jquery.js?ver=1.10.2',
						3 => 'http://www.theharrington.com/v3/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.2.1',
						4 => 'http://www.theharrington.com/v3/wp-content/themes/harrington/assets/js/bootstrap.min.js?ver=1.0',
						5 => 'http://www.theharrington.com/v3/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/ajax/static/ajax.js?ver=3.6.1',
						6 => 'http://www.theharrington.com/v3/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/lightbox/static/lightbox_context.js?ver=3.6.1',
						7 => 'http://www.theharrington.com/v3/wp-content/plugins/easy-fancybox/fancybox/jquery.fancybox-1.3.6.pack.js?ver=1.5.6',
						8 => 'http://www.theharrington.com/v3/wp-content/plugins/easy-fancybox/jquery.mousewheel.pack.js?ver=3.1.3',
						9 => 'http://www.theharrington.com/v3/wp-content/plugins/easy-fancybox/jquery.easing.pack.js?ver=1.3',
					),
				),
				'include-body' => array(
					'files' => array(
						0 => 'v4/wp-content/themes/harrington/assets/js/header.js',
					),
				),
			),
			'page-the-harrington' => array(
				'include' => array(
					'files' => array(
						0 => 'http://www.theharrington.com/v3/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/lightbox/static/fancybox/nextgen_fancybox_init.js?ver=3.6.1',
						1 => 'http://www.theharrington.com/v3/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/nextgen_gallery_display/static/common.js?ver=3.6.1',
						2 => 'http://www.theharrington.com/v3/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/nextgen_basic_gallery/static/thumbnails/nextgen_basic_thumbnails.js?ver=3.6.1',
						3 => 'http://www.theharrington.com/v3/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/lightbox/static/fancybox/jquery.easing-1.3.pack.js?ver=3.6.1',
						4 => 'http://www.theharrington.com/v3/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/lightbox/static/fancybox/jquery.fancybox-1.3.4.pack.js?ver=3.6.1',
					),
				),
			),
			'page-properties' => array(
				'include' => array(
					'files' => array(
						0 => 'v4/wp-content/themes/harrington/assets/js/bootstrap-multiselect.js',
					),
				),
				'include-body' => array(
					'files' => array(
						0 => 'v4/wp-content/themes/harrington/assets/js/properties.js',
					),
				),
			),
			'page-availability' => array(
				'include-body' => array(
					'files' => array(
						0 => 'v4/wp-content/themes/harrington/assets/js/availability.js',
					),
				),
			),
			'archive' => array(
				'include-body' => array(
					'files' => array(
						0 => 'v4/wp-content/themes/harrington/assets/js/archive.js',
					),
				),
			),
		),
	),
	'minify.css.groups' => array(
		'3919b' => array(
			'default' => array(
				'include' => array(
					'files' => array(
						0 => 'http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css',
						1 => 'http://www.theharrington.com/v3/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/nextgen_gallery_display/static/nextgen_gallery_related_images.css?ver=3.6.1',
						2 => 'http://www.theharrington.com/v3/wp-content/themes/harrington/assets/css/bootstrapwp.css?ver=1.0',
						3 => 'http://www.theharrington.com/v3/wp-content/plugins/easy-fancybox/fancybox/jquery.fancybox-1.3.6.pack.css?ver=1.5.6',
						4 => 'http://www.theharrington.com/v3/wp-content/themes/harrington/style.css?ver=3.6.1',
					),
				),
			),
			'page-the-harrington' => array(
				'include' => array(
					'files' => array(
						0 => 'http://www.theharrington.com/v3/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/lightbox/static/fancybox/jquery.fancybox-1.3.4.css?ver=3.6.1',
						1 => 'http://www.theharrington.com/v3/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/nextgen_basic_gallery/static/thumbnails/nextgen_basic_thumbnails.css?ver=3.6.1',
						2 => 'http://www.theharrington.com/v3/wp-content/plugins/nextgen-gallery/products/photocrati_nextgen/modules/nextgen_pagination/static/style.css?ver=3.6.1',
						3 => 'http://www.theharrington.com/v3/wp-content/ngg_styles/nggallery.css?ver=3.6.1',
					),
				),
			),
		),
	),
	'plugin.type' => '',
	'minify.auto.disable_filename_length_test' => false,
	'minify.cache.files' => array(
		0 => 'https://ajax.googleapis.com',
	),
	'pgcache.cache.home' => true,
	'pgcache.reject.front_page' => false,
	'pgcache.cache.feed' => true,
	'pgcache.cache.ssl' => false,
	'pgcache.cache.404' => false,
	'pgcache.check.domain' => false,
	'pgcache.reject.logged' => true,
	'pgcache.reject.logged_roles' => false,
	'pgcache.reject.roles' => array(
		0 => '',
	),
	'pgcache.prime.enabled' => true,
	'pgcache.prime.interval' => 900,
	'pgcache.prime.limit' => 10,
	'pgcache.prime.sitemap' => 'www.theharrington.com/sitemap.xml',
	'pgcache.prime.post.enabled' => true,
	'pgcache.purge.front_page' => false,
	'pgcache.purge.home' => true,
	'pgcache.purge.post' => true,
	'pgcache.purge.feed.blog' => true,
	'pgcache.purge.comments' => false,
	'pgcache.purge.author' => false,
	'pgcache.purge.terms' => false,
	'pgcache.purge.feed.comments' => false,
	'pgcache.purge.feed.author' => false,
	'pgcache.purge.feed.terms' => false,
	'pgcache.purge.archive.daily' => false,
	'pgcache.purge.archive.monthly' => false,
	'pgcache.purge.archive.yearly' => false,
	'pgcache.purge.feed.types' => array(
		0 => 'rss2',
	),
	'pgcache.purge.postpages_limit' => 10,
	'pgcache.purge.pages' => array(
		0 => '',
	),
	'pgcache.purge.sitemap_regex' => '([a-z0-9_\\-]*?)sitemap([a-z0-9_\\-]*)?\\.xml',
	'pgcache.late_init' => false,
	'pgcache.compatibility' => false,
	'pgcache.remove_charset' => false,
	'pgcache.file.gc' => 3600,
	'pgcache.comment_cookie_ttl' => 1800,
	'pgcache.accept.qs' => array(
		0 => '',
	),
	'pgcache.reject.ua' => array(
		0 => '',
	),
	'pgcache.reject.cookie' => array(
		0 => 'wptouch_switch_toggle',
	),
	'pgcache.reject.uri' => array(
		0 => 'wp-.*\\.php',
		1 => 'index\\.php',
	),
	'pgcache.accept.files' => array(
		0 => 'wp-comments-popup.php',
		1 => 'wp-links-opml.php',
		2 => 'wp-locations.php',
	),
	'pgcache.accept.uri' => array(
		0 => 'sitemap(_index)?\\.xml(\\.gz)?',
		1 => '[a-z0-9_\\-]+-sitemap([0-9]+)?\\.xml(\\.gz)?',
	),
	'browsercache.replace.exceptions' => array(
		0 => '',
	),
	'browsercache.no404wp' => false,
	'browsercache.no404wp.exceptions' => array(
		0 => 'robots\\.txt',
		1 => 'sitemap(_index)?\\.xml(\\.gz)?',
		2 => '[a-z0-9_\\-]+-sitemap([0-9]+)?\\.xml(\\.gz)?',
	),
	'browsercache.cssjs.last_modified' => true,
	'browsercache.cssjs.expires' => true,
	'browsercache.cssjs.lifetime' => 31536000,
	'browsercache.cssjs.cache.control' => true,
	'browsercache.cssjs.cache.policy' => 'cache_public_maxage',
	'browsercache.cssjs.etag' => true,
	'browsercache.cssjs.w3tc' => true,
	'browsercache.cssjs.compression' => true,
	'browsercache.cssjs.replace' => true,
	'browsercache.cssjs.nocookies' => true,
	'browsercache.html.last_modified' => true,
	'browsercache.html.expires' => true,
	'browsercache.html.lifetime' => 3600,
	'browsercache.html.cache.control' => true,
	'browsercache.html.cache.policy' => 'cache_public_maxage',
	'browsercache.html.etag' => true,
	'browsercache.html.w3tc' => true,
	'browsercache.html.compression' => true,
	'browsercache.other.last_modified' => true,
	'browsercache.other.expires' => true,
	'browsercache.other.lifetime' => 31536000,
	'browsercache.other.cache.control' => true,
	'browsercache.other.cache.policy' => 'cache_public_maxage',
	'browsercache.other.etag' => true,
	'browsercache.other.w3tc' => true,
	'browsercache.other.compression' => true,
	'browsercache.other.replace' => true,
	'browsercache.other.nocookies' => true,
	'browsercache.timestamp' => '1399661904',
);