document.createElement('article');
document.createElement('section');
document.createElement('aside');
document.createElement('hgroup');
document.createElement('nav');
document.createElement('header'); 
document.createElement('footer');
document.createElement('figure');
document.createElement('figcaption'); 